# yaml-cpp online: https://yaml-online-parser.appspot.com/
# suppose m shards and n warehouse each shard; 
# the first replica to be the leader by default
# https://aju9mlkupe.feishu.cn/docs/doccnG7AZ1gjFmo9CcgRMidJO5f Port allocation policy

shards: 2  # number of shards
replicas: 0 # number of replicas
warehouses: 2  # number of warehouses per shard, keep same as the tpcc worker threads
localhost:
  - name: shard0
    index: 0
    ip:   127.0.0.1
    port: 8000
  - name: shard1
    index: 1
    ip:   127.0.0.1
    port: 8000

memlocalhost: 6001 # mem control port
memlearner: 6001
memp1: 6002
memp2: 6003
